#!/bin/sh

PG_INCLUDE=$(pkg-config --cflags-only-I libpq | sed s'/^-I//g' | xargs)
SDB_TYPE_HEADER=${DBDB_SOURCE_DIR}/src/lib/sdb_type.h

mkdir -p build
cat > ${SDB_TYPE_HEADER} << EOF
/*-------------------------------------------------------------------------
*
* sdb_type.h
*    Macro definitions for sdb_type
*
* Copyright (c) 2020-2021, Bing Liu(spadcn@gmail.com)
*
* NOTES
*  ******************************
*  *** DO NOT EDIT THIS FILE! ***
*  ******************************
*
*  It has been GENERATED by src/lib/gen_type.sh
*
*-------------------------------------------------------------------------
*/
#ifndef SDB_TYPE_H
#define SDB_TYPE_H

EOF

cat "${PG_INCLUDE}/server/catalog/pg_type_d.h" | egrep "^#define[ _A-Z0-9]+OID [1-9]" >> ${SDB_TYPE_HEADER}
cat >> ${SDB_TYPE_HEADER} <<EOF

#endif  /* END SDB_TYPE_H */
EOF
